# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Signal_viewer.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Signalviewingwindow(object):
    def setupUi(self, Signalviewingwindow):
        Signalviewingwindow.setObjectName("Signalviewingwindow")
        Signalviewingwindow.resize(1121, 867)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        Signalviewingwindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(Signalviewingwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ViewPortUp = MplWidget(self.centralwidget)
        self.ViewPortUp.setGeometry(QtCore.QRect(40, 89, 600, 271))
        self.ViewPortUp.setObjectName("ViewPortUp")
        self.viewPortDown = MplWidget(self.centralwidget)
        self.viewPortDown.setGeometry(QtCore.QRect(40, 469, 600, 271))
        self.viewPortDown.setObjectName("viewPortDown")
        self.horizontalSlidingDown = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlidingDown.setGeometry(QtCore.QRect(40, 750, 600, 30))
        self.horizontalSlidingDown.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlidingDown.setObjectName("horizontalSlidingDown")
        self.verticalSlidingDown = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlidingDown.setGeometry(QtCore.QRect(10, 469, 25, 271))
        self.verticalSlidingDown.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlidingDown.setObjectName("verticalSlidingDown")
        self.VerticalSlidingUp = QtWidgets.QSlider(self.centralwidget)
        self.VerticalSlidingUp.setGeometry(QtCore.QRect(10, 89, 25, 271))
        self.VerticalSlidingUp.setOrientation(QtCore.Qt.Vertical)
        self.VerticalSlidingUp.setObjectName("VerticalSlidingUp")
        self.horizontalSlidingUp = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlidingUp.setGeometry(QtCore.QRect(40, 370, 600, 30))
        self.horizontalSlidingUp.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlidingUp.setObjectName("horizontalSlidingUp")
        self.zoomInDown = QtWidgets.QPushButton(self.centralwidget)
        self.zoomInDown.setGeometry(QtCore.QRect(70, 780, 93, 28))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("zoom-in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomInDown.setIcon(icon)
        self.zoomInDown.setObjectName("zoomInDown")
        self.zoomOutDown = QtWidgets.QPushButton(self.centralwidget)
        self.zoomOutDown.setGeometry(QtCore.QRect(190, 780, 93, 28))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Zoom-Out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomOutDown.setIcon(icon1)
        self.zoomOutDown.setIconSize(QtCore.QSize(15, 15))
        self.zoomOutDown.setObjectName("zoomOutDown")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(650, 90, 451, 291))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(4)
        self.frame.setObjectName("frame")
        self.browseFilesUp = QtWidgets.QPushButton(self.frame)
        self.browseFilesUp.setGeometry(QtCore.QRect(10, 240, 251, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.browseFilesUp.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("File.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.browseFilesUp.setIcon(icon2)
        self.browseFilesUp.setIconSize(QtCore.QSize(15, 15))
        self.browseFilesUp.setObjectName("browseFilesUp")
        self.signalTitleLabelUp = QtWidgets.QLabel(self.frame)
        self.signalTitleLabelUp.setGeometry(QtCore.QRect(10, 206, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.signalTitleLabelUp.setFont(font)
        self.signalTitleLabelUp.setObjectName("signalTitleLabelUp")
        self.customSignalNameUp = QtWidgets.QLineEdit(self.frame)
        self.customSignalNameUp.setGeometry(QtCore.QRect(100, 216, 161, 18))
        self.customSignalNameUp.setObjectName("customSignalNameUp")
        self.pausePlayUp = QtWidgets.QPushButton(self.frame)
        self.pausePlayUp.setGeometry(QtCore.QRect(270, 240, 171, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pausePlayUp.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("pauseplay-removebg-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pausePlayUp.setIcon(icon3)
        self.pausePlayUp.setObjectName("pausePlayUp")
        self.selectChannelLabelUp = QtWidgets.QLabel(self.frame)
        self.selectChannelLabelUp.setGeometry(QtCore.QRect(10, 16, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.selectChannelLabelUp.setFont(font)
        self.selectChannelLabelUp.setObjectName("selectChannelLabelUp")
        self.channelSelectorUp = QtWidgets.QComboBox(self.frame)
        self.channelSelectorUp.setGeometry(QtCore.QRect(140, 16, 281, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.channelSelectorUp.setFont(font)
        self.channelSelectorUp.setObjectName("channelSelectorUp")
        self.colorSelectorUp = QtWidgets.QPushButton(self.frame)
        self.colorSelectorUp.setGeometry(QtCore.QRect(10, 76, 130, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.colorSelectorUp.setFont(font)
        self.colorSelectorUp.setObjectName("colorSelectorUp")
        self.hideGraphUp = QtWidgets.QCheckBox(self.frame)
        self.hideGraphUp.setGeometry(QtCore.QRect(150, 75, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hideGraphUp.setFont(font)
        self.hideGraphUp.setObjectName("hideGraphUp")
        self.cineSpeedLabelUp = QtWidgets.QLabel(self.frame)
        self.cineSpeedLabelUp.setGeometry(QtCore.QRect(20, 146, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cineSpeedLabelUp.setFont(font)
        self.cineSpeedLabelUp.setObjectName("cineSpeedLabelUp")
        self.cineSpeedSelectorUp = QtWidgets.QSlider(self.frame)
        self.cineSpeedSelectorUp.setGeometry(QtCore.QRect(130, 146, 200, 30))
        self.cineSpeedSelectorUp.setOrientation(QtCore.Qt.Horizontal)
        self.cineSpeedSelectorUp.setObjectName("cineSpeedSelectorUp")
        self.rewindUp = QtWidgets.QPushButton(self.frame)
        self.rewindUp.setGeometry(QtCore.QRect(270, 206, 171, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rewindUp.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Reset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rewindUp.setIcon(icon4)
        self.rewindUp.setObjectName("rewindUp")
        self.moveToOtherGraphUp = QtWidgets.QPushButton(self.frame)
        self.moveToOtherGraphUp.setGeometry(QtCore.QRect(220, 76, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.moveToOtherGraphUp.setFont(font)
        self.moveToOtherGraphUp.setObjectName("moveToOtherGraphUp")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(340, 136, 81, 45))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.frame_2.setFont(font)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(4)
        self.frame_2.setMidLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.cineSpeedNumberUp = QtWidgets.QLabel(self.frame_2)
        self.cineSpeedNumberUp.setGeometry(QtCore.QRect(0, 10, 81, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cineSpeedNumberUp.setFont(font)
        self.cineSpeedNumberUp.setAlignment(QtCore.Qt.AlignCenter)
        self.cineSpeedNumberUp.setObjectName("cineSpeedNumberUp")
        self.zoomOutUp = QtWidgets.QPushButton(self.centralwidget)
        self.zoomOutUp.setGeometry(QtCore.QRect(190, 400, 93, 28))
        self.zoomOutUp.setIcon(icon1)
        self.zoomOutUp.setIconSize(QtCore.QSize(15, 15))
        self.zoomOutUp.setObjectName("zoomOutUp")
        self.zoomInUp = QtWidgets.QPushButton(self.centralwidget)
        self.zoomInUp.setGeometry(QtCore.QRect(70, 400, 93, 28))
        self.zoomInUp.setIcon(icon)
        self.zoomInUp.setObjectName("zoomInUp")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(650, 470, 451, 291))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setLineWidth(4)
        self.frame_3.setObjectName("frame_3")
        self.browseFilesDown = QtWidgets.QPushButton(self.frame_3)
        self.browseFilesDown.setGeometry(QtCore.QRect(10, 250, 251, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.browseFilesDown.setFont(font)
        self.browseFilesDown.setIcon(icon2)
        self.browseFilesDown.setIconSize(QtCore.QSize(15, 15))
        self.browseFilesDown.setObjectName("browseFilesDown")
        self.signalTitleLabelDown = QtWidgets.QLabel(self.frame_3)
        self.signalTitleLabelDown.setGeometry(QtCore.QRect(10, 210, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.signalTitleLabelDown.setFont(font)
        self.signalTitleLabelDown.setObjectName("signalTitleLabelDown")
        self.customSignalNameDown = QtWidgets.QLineEdit(self.frame_3)
        self.customSignalNameDown.setGeometry(QtCore.QRect(100, 220, 161, 18))
        self.customSignalNameDown.setObjectName("customSignalNameDown")
        self.pausePlayDown = QtWidgets.QPushButton(self.frame_3)
        self.pausePlayDown.setGeometry(QtCore.QRect(270, 250, 171, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pausePlayDown.setFont(font)
        self.pausePlayDown.setIcon(icon3)
        self.pausePlayDown.setObjectName("pausePlayDown")
        self.selectChannelLabelDown = QtWidgets.QLabel(self.frame_3)
        self.selectChannelLabelDown.setGeometry(QtCore.QRect(10, 20, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.selectChannelLabelDown.setFont(font)
        self.selectChannelLabelDown.setObjectName("selectChannelLabelDown")
        self.channelSelectorDown = QtWidgets.QComboBox(self.frame_3)
        self.channelSelectorDown.setGeometry(QtCore.QRect(140, 20, 281, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.channelSelectorDown.setFont(font)
        self.channelSelectorDown.setObjectName("channelSelectorDown")
        self.selectColorDown = QtWidgets.QPushButton(self.frame_3)
        self.selectColorDown.setGeometry(QtCore.QRect(10, 80, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.selectColorDown.setFont(font)
        self.selectColorDown.setObjectName("selectColorDown")
        self.hideGraphDown = QtWidgets.QCheckBox(self.frame_3)
        self.hideGraphDown.setGeometry(QtCore.QRect(140, 79, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hideGraphDown.setFont(font)
        self.hideGraphDown.setObjectName("hideGraphDown")
        self.cineSpeedLabelDown = QtWidgets.QLabel(self.frame_3)
        self.cineSpeedLabelDown.setGeometry(QtCore.QRect(20, 150, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cineSpeedLabelDown.setFont(font)
        self.cineSpeedLabelDown.setObjectName("cineSpeedLabelDown")
        self.cineSpeedSelectorDown = QtWidgets.QSlider(self.frame_3)
        self.cineSpeedSelectorDown.setGeometry(QtCore.QRect(130, 150, 200, 30))
        self.cineSpeedSelectorDown.setOrientation(QtCore.Qt.Horizontal)
        self.cineSpeedSelectorDown.setObjectName("cineSpeedSelectorDown")
        self.rewindDown = QtWidgets.QPushButton(self.frame_3)
        self.rewindDown.setGeometry(QtCore.QRect(270, 210, 171, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rewindDown.setFont(font)
        self.rewindDown.setIcon(icon4)
        self.rewindDown.setObjectName("rewindDown")
        self.moveToOtherGraphDown = QtWidgets.QPushButton(self.frame_3)
        self.moveToOtherGraphDown.setGeometry(QtCore.QRect(220, 80, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.moveToOtherGraphDown.setFont(font)
        self.moveToOtherGraphDown.setObjectName("moveToOtherGraphDown")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setGeometry(QtCore.QRect(340, 140, 81, 45))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.frame_4.setFont(font)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setLineWidth(4)
        self.frame_4.setMidLineWidth(0)
        self.frame_4.setObjectName("frame_4")
        self.cineSpeedNumberDown = QtWidgets.QLabel(self.frame_4)
        self.cineSpeedNumberDown.setGeometry(QtCore.QRect(0, 10, 81, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cineSpeedNumberDown.setFont(font)
        self.cineSpeedNumberDown.setAlignment(QtCore.Qt.AlignCenter)
        self.cineSpeedNumberDown.setObjectName("cineSpeedNumberDown")
        self.extractUp = QtWidgets.QPushButton(self.centralwidget)
        self.extractUp.setGeometry(QtCore.QRect(930, 390, 171, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.extractUp.setFont(font)
        self.extractUp.setObjectName("extractUp")
        self.extractDown = QtWidgets.QPushButton(self.centralwidget)
        self.extractDown.setGeometry(QtCore.QRect(930, 770, 171, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.extractDown.setFont(font)
        self.extractDown.setObjectName("extractDown")
        self.linkingGraphs = QtWidgets.QCheckBox(self.centralwidget)
        self.linkingGraphs.setGeometry(QtCore.QRect(940, 430, 160, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.linkingGraphs.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Link.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.linkingGraphs.setIcon(icon5)
        self.linkingGraphs.setObjectName("linkingGraphs")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 20, 711, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.captureSignalUp = QtWidgets.QPushButton(self.centralwidget)
        self.captureSignalUp.setGeometry(QtCore.QRect(750, 390, 171, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.captureSignalUp.setFont(font)
        self.captureSignalUp.setObjectName("captureSignalUp")
        self.captureSignalDown = QtWidgets.QPushButton(self.centralwidget)
        self.captureSignalDown.setGeometry(QtCore.QRect(750, 770, 171, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.captureSignalDown.setFont(font)
        self.captureSignalDown.setObjectName("captureSignalDown")
        Signalviewingwindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Signalviewingwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1121, 26))
        self.menubar.setObjectName("menubar")
        Signalviewingwindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Signalviewingwindow)
        self.statusbar.setObjectName("statusbar")
        Signalviewingwindow.setStatusBar(self.statusbar)
        self.actionOpen_File_UP = QtWidgets.QAction(Signalviewingwindow)
        self.actionOpen_File_UP.setObjectName("actionOpen_File_UP")
        self.actionSave_To_Pdf = QtWidgets.QAction(Signalviewingwindow)
        self.actionSave_To_Pdf.setObjectName("actionSave_To_Pdf")

        self.retranslateUi(Signalviewingwindow)
        QtCore.QMetaObject.connectSlotsByName(Signalviewingwindow)

    def retranslateUi(self, Signalviewingwindow):
        _translate = QtCore.QCoreApplication.translate
        Signalviewingwindow.setWindowTitle(_translate("Signalviewingwindow", "Multichannel Signal Viewer"))
        self.zoomInDown.setText(_translate("Signalviewingwindow", "Zoom In"))
        self.zoomOutDown.setText(_translate("Signalviewingwindow", "Zoom Out"))
        self.browseFilesUp.setText(_translate("Signalviewingwindow", "Browse "))
        self.signalTitleLabelUp.setText(_translate("Signalviewingwindow", "Signal Title:"))
        self.pausePlayUp.setText(_translate("Signalviewingwindow", "Pause/Play"))
        self.selectChannelLabelUp.setText(_translate("Signalviewingwindow", "Select Channel:"))
        self.colorSelectorUp.setText(_translate("Signalviewingwindow", "Select Color"))
        self.hideGraphUp.setText(_translate("Signalviewingwindow", "Hide"))
        self.cineSpeedLabelUp.setText(_translate("Signalviewingwindow", " Cine Speed"))
        self.rewindUp.setText(_translate("Signalviewingwindow", "Rewind"))
        self.moveToOtherGraphUp.setText(_translate("Signalviewingwindow", "Move to other Graph"))
        self.cineSpeedNumberUp.setText(_translate("Signalviewingwindow", "0"))
        self.zoomOutUp.setText(_translate("Signalviewingwindow", "Zoom Out"))
        self.zoomInUp.setText(_translate("Signalviewingwindow", "Zoom In"))
        self.browseFilesDown.setText(_translate("Signalviewingwindow", "Browse "))
        self.signalTitleLabelDown.setText(_translate("Signalviewingwindow", "Signal Title:"))
        self.pausePlayDown.setText(_translate("Signalviewingwindow", "Pause/Play"))
        self.selectChannelLabelDown.setText(_translate("Signalviewingwindow", "Select Channel:"))
        self.selectColorDown.setText(_translate("Signalviewingwindow", "Select Color"))
        self.hideGraphDown.setText(_translate("Signalviewingwindow", "Hide"))
        self.cineSpeedLabelDown.setText(_translate("Signalviewingwindow", " Cine Speed"))
        self.rewindDown.setText(_translate("Signalviewingwindow", "Rewind"))
        self.moveToOtherGraphDown.setText(_translate("Signalviewingwindow", "Move to other Graph"))
        self.cineSpeedNumberDown.setText(_translate("Signalviewingwindow", "0"))
        self.extractUp.setText(_translate("Signalviewingwindow", "Extract"))
        self.extractDown.setText(_translate("Signalviewingwindow", "Extract"))
        self.linkingGraphs.setText(_translate("Signalviewingwindow", "Link Graphs"))
        self.label.setText(_translate("Signalviewingwindow", "Multi Channel Signal Viewer"))
        self.captureSignalUp.setText(_translate("Signalviewingwindow", "Capture"))
        self.captureSignalDown.setText(_translate("Signalviewingwindow", "Capture"))
        self.actionOpen_File_UP.setText(_translate("Signalviewingwindow", "Open File"))
        self.actionSave_To_Pdf.setText(_translate("Signalviewingwindow", "Save To Pdf"))

from mplwidget import MplWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Signalviewingwindow = QtWidgets.QMainWindow()
    ui = Ui_Signalviewingwindow()
    ui.setupUi(Signalviewingwindow)
    Signalviewingwindow.show()
    sys.exit(app.exec_())

